ALTER TABLE UMPAY.T_COUPON_RULE ADD COLUMN RULETYPE SMALLINT NOT NULL DEFAULT 0;
COMMENT ON COLUMN UMPAY.T_COUPON_RULE_RULETYPE IS '0-不能批量导出 1-能批量导出';

ALTER TABLE UMPAY.T_COUPON_RULE ADD COLUMN ORIGINALPRICE DECIMAL(12,0) NOT NULL DEFAULT 0;
COMMENT ON COLUMN UMPAY.T_COUPON_RULE.ORIGINALPRICE IS '兑换码面值(单位分)';

ALTER TABLE UMPAY.T_COUPON_RULE ADD COLUMN EXPORT SMALLINT NOT NULL DEFAULT 1;
COMMENT ON COLUMN UMPAY.T_COUPON_RULE.EXPORT IS '0-已导出, 1-未导出';

ALTER TABLE UMPAY.T_COUPON_CODE ADD COLUMN ORIGINALPRICE DECIMAL(12,0) NOT NULL DEFAULT 0;
COMMENT ON COLUMN UMPAY.T_COUPON_CODE.ORIGINALPRICE IS '兑换码面值(单位分)';