ALTER TABLE UMPAY.T_MER_BANK ADD MODLOCK SMALLINT NOT NULL DEFAULT 0;
COMMENT ON COLUMN UMPAY.T_MER_BANK.MODLOCK IS '修改锁';

ALTER TABLE UMPAY.T_GOODS_BANK ADD MODLOCK SMALLINT NOT NULL DEFAULT 0;
COMMENT ON COLUMN UMPAY.T_GOODS_BANK.MODLOCK IS '修改锁';


ALTER TABLE UMPAY.T_SERVICE_INF ADD CATEGORY CHAR(8) NOT NULL DEFAULT '';
COMMENT ON COLUMN UMPAY.T_SERVICE_INF.CATEGORY IS '计费代码分类 101数字及游戏点卡、102电子书、103邮箱、104视频、105软件、106保险、107彩票';